server {
    listen 80;
    server_name localhost;

    # Frontend (Angular)
    root /usr/share/nginx/html;
    index index.html;

    # Routes Angular (SPA fallback)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers l'API Laravel (PHP-FPM)
    location ~ ^/(api|sanctum|up) {
        root /var/www/html/public;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        root /var/www/html/public;
        fastcgi_pass api:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
